Mío-4/airline/airline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/', include("flights.urls")),
    path('users/', include("users.urls")),
]

Mío-4/airline/flights/urls.py
from django.urls import path, include

from . import views

app_name = 'flights'

urlpatterns = [
    path('', views.home_view, name="flights"),
    path('<int:fl_id>/', views.flight_view, name= 'flight_view'),
    path('<int:fl_id>/book', views.flight_book, name= 'flight_book'),
]

Mío-4/airline/users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login_view, name= 'login_view'),
    path('logout/', views.logout_view, name= 'logout_view'),
]

Mío-4/airline/flights/models.py
from django.db import models
from django.urls import reverse

class Airport (models.Model):
	code = models.CharField (max_length=3)
	city = models.CharField (max_length=64)

	def __str__(self):
		return f"{self.city} ({self.code})"

class Flight (models.Model):
	origin = models.ForeignKey (Airport, on_delete=models.CASCADE, related_name='departures')
	destination = models.ForeignKey (Airport, on_delete=models.CASCADE, related_name='arrivals')
	duration = models.IntegerField ()

	def __str__ (self):
		#return (self.origin + " - " + self.destination + " in "+ str(self.duration)+" minutes.")
		#return f"{self.origin} - {self.destination} in {str(self.duration)} minutes"
		return "{} - {} in {} minutes".format (self.origin, self.destination, str(self.duration))

	def get_absolute_url(self):
		return reverse('flights:flight_view', args=[self.id])

class Passenger(models.Model):
	first = models.CharField (max_length=64)
	last = models.CharField (max_length=64)
	flight = models.ManyToManyField (Flight, blank=True, null=True, related_name='passengers')

	def __str__ (self):
		return f"{self.last}, {self.first}"

Mío-4/airline/users/models.py
from django.db import models

# Create your models here.

Mío-4/airline/flights/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Flight, Passenger

def home_view (request):
	qs = Flight.objects.all()

	template_name = 'flights/home.html'

	return render (request, template_name, {'flights': qs})

def flight_view (request, fl_id):
	obj = Flight.objects.get(id=fl_id)
	pas = obj.passengers.all()
	non_pas = Passenger.objects.exclude(flight=obj).all()

	template_name = 'flights/flight.html'

	return render (request, template_name, {'flight': obj, 'passengers': pas, 'non_passengers': non_pas})

def flight_book (request, fl_id):
	print (request.method)

	if request.method == 'POST':
		obj = Flight.objects.get(id=fl_id)
		passenger = Passenger.objects.get(id=int(request.POST ['passenger']))
		passenger.flight.add(obj)

		return HttpResponseRedirect (reverse('flights:flight_view', args=(obj.id,)))

	


Mío-4/airline/users/views.py
from django.contrib.auth import authenticate, login, logout

from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

def index(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect (reverse("users:login_view"))

	return render(request, "users/user.html")

def login_view(request):
	template_name = "users/login.html"

	if request.method =='POST':
		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(request, username=username, password=password)
		print (user, request.POST['username'])

		if user is not None:
			login (request, user)

			return HttpResponseRedirect (reverse("users:index"))
		else:
			return render (request, template_name, {"message": "Invalid credentials"})	

	return render (request, template_name, {})

def logout_view(request):
	logout (request)

	return HttpResponseRedirect (reverse("users:login_view"))

Mío-4/airline/flights/templates/flights/flight.html
<!DOCTYPE html>
<html>
<head>
	<title>From {{ flight.origin }} to {{ flight.destination }}</title>
</head>
<body>
	<h1>This the Flight n° {{ flight.id }}</h1>
	<h3>From {{ flight.origin }}</h3>
	<h3>to {{ flight.destination }}</h3>
	<p>The duration of the flight is {{ flight.duration }} minutes</p>
	<br>
	<hr>
	<br>

	<ul>
		{% for pas in passengers %}
			<li>Pasajero n° {{ pas.id }}: {{ pas }}</li>
		{% empty %}
			<li>No passengers</li>
		{% endfor %}
	</ul>

	<h2>Add Passenger</h2>
	<form action="{% url 'flights:flight_book' flight.id %}" method="POST">
		{% csrf_token %}
		<select name='passenger'>
			{% for tipo in non_passengers %}
				<option value="{{ tipo.id }}">{{ tipo }}</option>
			{% endfor %}
		</select>
	 	<input type="submit">
	</form>

	<a href="{% url 'flights:flights'%} ">Go back</a>
		
</body>
</html>

Mío-4/airline/flights/templates/flights/home.html
<!DOCTYPE html>
<html>
<head>
	<title>Flights</title>
</head>
<body>
	<h1>Flights</h1>
	<ul>
	{% for flight in flights  %}
		<li><a href="{{ flight.get_absolute_url }}">Vuelo {{ flight.id }}</a>: From {{flight.origin}} to {{flight.destination}}</li>
	{% endfor  %}
	</ul>
</body>
</html>

Mío-4/airline/users/templates/users/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
</head>
<body>

	{% if message %}
		<div>{{ message }}</div>
	{% endif %}

	<form action="{% url 'users:login_view' %}" method="POST">
		{% csrf_token %}
		<input type="text" name="username" placeholder="Username">
		<input type="password" name="password" placeholder="Password">
		<input type="submit" value="Login">
	</form>
</body>
</html>

Mío-4/airline/users/templates/users/user.html
<!DOCTYPE html>
<html>
<head>
	<title>User</title>
</head>
<body>
    <h1>Welcome, {{ request.user.first_name }}</h1>

    <ul>
        <li>Username: {{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>

    <a href="{% url 'users:logout_view' %}">Log Out</a>
</body>
</html>